### ISSUE TITLE
Error: Cannot find module 'npm' on Windows

### ISSUE THREAD

**Issue by xuchaoying** [dracupid/global-npm#5]
When run an app in **npm scripts**, `global-npm` report an error that cannot find 'npm'.

![image](https://user-images.githubusercontent.com/8073251/69840497-c2c05380-1296-11ea-9cf9-a0e3c718c284.png)

OS: **Windows 10**
node: v8

---

It seems to be related to the environment variable `npm_execpath`.

When echo in bash directly, it's `undefined`:

![image](https://user-images.githubusercontent.com/8073251/69840698-67429580-1297-11ea-88a0-601cc1f4074e.png)

But when echo in npm script:

![image](https://user-images.githubusercontent.com/8073251/69840760-a1ac3280-1297-11ea-87ff-5f62512567f8.png)
![image](https://user-images.githubusercontent.com/8073251/69840789-b8eb2000-1297-11ea-9036-b740a526bfa6.png)

It's a different path than `which npm`:

![image](https://user-images.githubusercontent.com/8073251/69840822-e9cb5500-1297-11ea-9fc1-2867640d9e25.png)
which is linked to `C:\Users\xucha\AppData\Roaming\nvm\v8.9.2\npm` here

**Comment by relu91** [comment]
I encounter the same problem. I just want to add that `npm_exacpath` point to a valid js file:
`C:\Users\reluc\AppData\Roaming\nvm\v10.16.0\node_modules\npm\bin\npm-cli.js`. While the library tries to require this path:
`C:\Users\reluc\AppData\Roaming\nvm\v10.16.0\node_modules\npm\bin\node_modules\npm` 
which does not point to a valid location in the filesystem.

**Comment by dracupid** [comment]
`npm_execpath` is an environment variable set by npm itself, which only exists when you run npm scripts. The path in `npm_execpath` is the same as the bin path of`npm` command you use to run `npm run xxx`. So I prefer to use this variable at first because it is likely an official way.
If you have tried to run`ls -al $(which npm)`, you will find that this path is just a symbol link to `npm/bin/npm-cli.js`

This issue may be related to the difference between nvm and a standard installation. I will try to fix it.

**Comment by dracupid** [comment]
try 0.4.1 ?

**Comment by relu91** [comment]
Tested. it is fixed in my case. Thank you for your time! 👍
